### ISSUE TITLE
Improvement: uninstall SQL table when module is uninstalled?

### ISSUE THREAD

**Issue by matks** [PrestaShop/ps_qualityassurance#11]
When module is uninstalled, SQL tables are not removed. This can be useful or this can be considered a mistake. Wdyt @PierreRambaud ?

**Comment by PierreRambaud** [comment]
It was not needed because of `CREATE TABLE IF NOT EXISTS` and because this module is here only for testing.
We can add it if needed

**Comment by matks** [comment]
So we keep the tables so that QA analysts do not lose their data if they uninstall it :) ? it's a feature

Approved 👍
